//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.OrderDetails = new HashSet<OrderDetail>();
            this.PaymentHistories = new HashSet<PaymentHistory>();
        }
    
        public string ID { get; set; }
        public Nullable<System.DateTime> NgayLapDon { get; set; }
        public Nullable<decimal> GiaTong { get; set; }
        public Nullable<decimal> AmountToMarketplace { get; set; }
        public Nullable<decimal> AmountToOrg { get; set; }
        public string IDCus { get; set; }
        public string PaymentMethod { get; set; }
        public Nullable<int> PaymentStatus { get; set; }
        public Nullable<int> OrderStatus { get; set; }
        public Nullable<System.DateTime> CreatedAt { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderDetail> OrderDetails { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PaymentHistory> PaymentHistories { get; set; }
    }
}
