//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BookStore.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PaymentHistory
    {
        public string ID { get; set; }
        public string OrderID { get; set; }
        public string PaymentMethodID { get; set; }
        public Nullable<decimal> AmountToMarketplace { get; set; }
        public Nullable<decimal> AmountToOrg { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
    
        public virtual Order Order { get; set; }
        public virtual PaymentMethod PaymentMethod { get; set; }
    }
}
